# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e544a3d1cbdbe9e9dea6bdb0f6dcb726728c4fdb89194c56ccc1490b9a9f5073680b16261dc533c2bf2013c8354701651a9503ec9b207043517dbc9b05ff2aa

test:
  secret_key_base: 1163b225fddd5d9d47f26fcc9031cf976d51cf844e8066aba8646b6024034d3368e86d3950c263f25833671767b0980345671e3c60349c9adec7f9857fbe933a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
